/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/axe.glb 
Author: Vanya Mazalevich (https://sketchfab.com/VanyaMazalevich)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/leviathan-axe-64a07e5622514582998f7fe5986bf0f2
Title: Leviathan axe
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/axe.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[0, 0, -Math.PI / 2]} scale={0.378}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.defaultMaterial.geometry} material={materials.Material__27} />
          <mesh geometry={nodes.defaultMaterial_1.geometry} material={materials.Material__27} />
          <mesh geometry={nodes.defaultMaterial_2.geometry} material={materials.Material__26} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/axe.glb')
